backend:
  name: github
  repo: littlefinger42/lauras-portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: animation
    label: Animation Item
    folder: static/animation
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: videoId, label: Youtube ID, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: illustration
    label: Illustration Item
    folder: static/illustration
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: illustration, label: Illustration Image, widget: image }
      - { name: body, label: Body, widget: markdown }