backend:
  name: github
  repo: littlefinger42/lauras-portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: portfolio
    label: Portfolio Item
    folder: static/portfolio
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: videoId, label: Youtube ID, widget: string }
      - { name: body, label: Body, widget: markdown }